---

- hosts: all
  become: true
  tasks:

  - name: upgrade and update cache
    apt:
      upgrade: dist
      update_cache: yes

  - name: insatll apache and php
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest


- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    apt:
      name:
        - samba
      state: latest
