---

- hosts: all
  become: true
  pre_tasks:

  - name: upgrade and update cache
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: Create user ugle
    tags: always
    user:
      name: ugle
      groups: sudo


- hosts: all
  become: true
  tasks:

  - name: insatll apache and php
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/
      owner: elgu
      group: sudo
      mode: 0644


- hosts: file_servers
  become: true
  tasks:

  - name: install samba
    tags: samba,ubuntu
    apt:
      name:
        - samba
      state: latest
    when: ansible_distribution == "Ubuntu"
